import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import "@fortawesome/fontawesome-free/css/all.min.css";
import 'bootstrap-css-only/css/bootstrap.min.css';
import 'mdbreact/dist/css/mdb.css';
import IntroSection from '../components/IntroSection';
import ImageInfoCard from '../components/ImageInfoCard';
import ImagePartnerCard from '../components/ImagePartnerCard';
import IntroVideoSection from '../components/IntroVideoSection';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Treenet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IntroSection/>
      <ImagePartnerCard/>
      <ImageInfoCard/>
    </div>
  )
}
